services:
  web:
    build: .
    ports:
      - "9000:9000"
    environment:
      - REDIS_URL=redis://redis:6379/0  # Use the service name 'redis'
    depends_on:
      - redis
    volumes:
      - ./:/app  # Maps ecom_draft to /app
  redis:
    image: redis:latest
